extends Node

const EQUIPMENT_TAGS = {
	"slot_types":[
		"HOLD_MODIFIERS",
		"CARGO_ACCESSORIES",
		"CREW_MODIFIERS",
		"LARGE_TORCH",
		"LARGE_RCS"
	],
	"equipment_types":[
		"EQUIPMENT_MANIPULATOR_LIGHT",
		"EQUIPMENT_HOLD_MODIFIER",
		"CARGO_ACCESSORIES",
		"CREW_MODIFIER",
		"THRUSTER_LARGE_MAIN_ENGINE"
	],
	"hardpoint_types":[
		"HARDPOINT_TURRET"
	],
	"slot_defaults":{
		"HARDPOINT_LOW_STRESS":[
			"EQUIPMENT_MANIPULATOR_LIGHT"
		],
		"HARDPOINT_HIGH_STRESS":[
			"EQUIPMENT_MANIPULATOR_LIGHT"
		],
		"HARDPOINT_SPINAL":[
			"EQUIPMENT_MANIPULATOR_LIGHT"
		],
		"HARDPOINT_TURRET":[
			"EQUIPMENT_TURRETS",
			"EQUIPMENT_NANODRONES"
		],
		"HOLD_MODIFIERS":[
			"EQUIPMENT_HOLD_MODIFIER"
		],
		"CARGO_ACCESSORIES":[
			"CARGO_ACCESSORIES"
		],
		"CREW_MODIFIERS":[
			"CREW_MODIFIER"
		],
		"LARGE_TORCH":[
			"THRUSTER_LARGE_MAIN_ENGINE"
		],
	}
}
const SLOT_TAGS = {
	
}
